public class Record
{
    public string membership_type { get; set; }
    public string title { get; set; }
    public string first_name { get; set; }
    public string middle_name { get; set; }
    public string last_name { get; set; }
    public string nickname { get; set; }
    public string suffix { get; set; }
    public string username { get; set; }
    public string gender { get; set; }
    public string club { get; set; }
    public string club_position { get; set; }
    public string district_defined_club_position { get; set; }
    public string district_position { get; set; }
    public string email { get; set; }
    public string alternate_email { get; set; }
    public string preferred_address { get; set; }
    public string preferred_address1 { get; set; }
    public string preferred_address2 { get; set; }
    public string preferred_city { get; set; }
    public string preferred_state { get; set; }
    public string preferred_zip_code { get; set; }
    public string preferred_country { get; set; }
    public string address_line_1 { get; set; }
    public string address_line_2 { get; set; }
    public string city { get; set; }
    public string state_province { get; set; }
    public string zip_postal_code { get; set; }
    public string country { get; set; }
    public string preferred_phone_type { get; set; }
    public string preferred_phone { get; set; }
    public string home_phone { get; set; }
    public string home_fax { get; set; }
    public string pager { get; set; }
    public string cell { get; set; }
    public string business_phone { get; set; }
    public string business_fax { get; set; }
    public string company_name { get; set; }
    public string position_title { get; set; }
    public string classification { get; set; }
    public string business_address1 { get; set; }
    public string business_address2 { get; set; }
    public string business_city { get; set; }
    public string business_state_province { get; set; }
    public string business_zip_postal_code { get; set; }
    public string business_country { get; set; }
    public DateTime date_of_birth { get; set; }
    public string spouse_partner_first_name { get; set; }
    public string spouse_partner_last_name { get; set; }
    public string spouse_partner_nick_name { get; set; }
    public DateTime spouse_partner_date_of_birth { get; set; }
    public DateTime anniversary { get; set; }
    public int member_no { get; set; }
    public string website_url { get; set; }
    public string membership { get; set; }
    public string office { get; set; }
    public string sponsor { get; set; }
    public DateTime date_joined_rotary { get; set; }
    public DateTime date_joined_club { get; set; }
    public int years_of_service_rotary { get; set; }
    public int years_of_service_club { get; set; }
    public string personal_url { get; set; }
    public DateTime termination_date { get; set; }
    public string reason_for_termination { get; set; }
    public DateTime date_created { get; set; }
    public DateTime date_modified { get; set; }
    public DateTime last_login { get; set; }
    public string club_mailing_address { get; set; }
    public string club_phone { get; set; }
    public string club_email { get; set; }
    public string club_website { get; set; }
    public string club_fax { get; set; }
    public string badge_no { get; set; }
    public string club_area { get; set; }
    public string club_assistant_area_governor { get; set; }
}
